=== wrb233/xml-dtd-schema/xml/partA-c/students不改.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generated by XMLSpy v2016 rel. 2 (http://www.altova.com) -->


<!ELEMENT students (student+)>
<!ELEMENT student (((firstname, lastname) | name), course+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!ELEMENT course (#PCDATA | name | submodule)*>     <!--this
construct would be problematic.But we can use a mandatory implementation-->

<!ELEMENT submodule (#PCDATA)>
<!ATTLIST students
	year CDATA #REQUIRED
>
<!ATTLIST student
	enrolmentDate CDATA #IMPLIED
>

=== wrb233/xml-dtd-schema/xml/partA-c/students不改.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE students SYSTEM "C:\Users\wl\Desktop\xml\partA-c\students不改.dtd">
<students year="2019-2020">
	<student enrolmentDate="2017">
		<name>John Smith</name>
		<course>
			<name>Software, Systems and Applications III</name>
			<submodule>Advanced Databases</submodule>
			<submodule>Web Technology</submodule>
		</course>
		<course>Computing Methodologies III</course>    <!--this
construct would be problematic.But we can use a mandatory implementation-->
	</student>
	<student enrolmentDate="2016">
		<firstname>Anna</firstname>
		<lastname>Brown</lastname>
		<course>
			<name>Software, Systems and Applications IV</name>
			<submodule>Semantic Web</submodule>
		</course>
		<course>Computing Methodologies IV</course>
	</student>
</students>
